services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: nbank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres -d nbank']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - nobugs-network
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: nobugsme/nbank:with_database_with_fix
    environment:
      ADMIN_USERNAME: admin
      ADMIN_PASSWORD: admin
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nbank
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - '4111:4111'
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ['CMD-SHELL', 'curl -f http://localhost:4111/actuator/health || exit 1']
      interval: 5s
      timeout: 3s
      retries: 20
    networks:
      - nobugs-network

  frontend:
    image: nobugsme/nbank-ui:with_nginx_with_send_transfer_fix
    expose:
      - '80'
    depends_on:
      - backend
    networks:
      - nobugs-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - nobugs-network

networks:
  nobugs-network:
    name: nobugs-network

volumes:
  postgres_data:
